### ISSUE TITLE
minie.getPropositions() -> getAttribution() working correctly?

### ISSUE THREAD

**Issue by chrisoutwright** [uma-pi1/minie#11]
I am evaluating Minie as OIE tool for my master thesis and encountered some issues, that I cannot trace back to them being implementation issues or being inherent in the model. To illustrate:

`Input sentence: Emily thought: 'Nobody is perfect'`

```
	Triple: "Emily"	"thought"	
	Factuality: (+,CT)	Attribution: NONE
	----------
	Triple: "Nobody"	"is"	"perfect"	
	Factuality: (+,CT)	Attribution: NONE
```

Sadly, Attribution seems to be working only for a limited set of verbs. Is this the correct behavior?

**Comment by gkiril** [comment]
The attribution is based on domain-independent verbs + the output of the dependency parse of the sentence. For more details, I kindly refer you the [paper](https://www.aclweb.org/anthology/D17-1278/).
