### ISSUE TITLE
Dictionary: Wikipedia: frequent relations and arguments (minie-resources/wiki-freq-args-mw.txt and /minie-resources/wiki-freq-rels-mw.txt) not available

### ISSUE THREAD

**Issue by heathersherry** [uma-pi1/minie#3]
May I ask another question? I would like to use the MinIE-Dictionary mode, and want to download "Dictionary: Wikipedia: frequent relations and arguments". However, the hyperlink you provide for download (http://dws.informatik.uni-mannheim.de/fileadmin/lehrstuehle/pi1/pi1/minie/wiki-freq-args-rels.zip) is no longer accessible.
Could you please fix this problem? Thanks a lot for your help!

**Comment by gkiril** [comment]
@heathersherry sorry for the late reply. The links are now fixed. 
Cheers!

**Comment by heathersherry** [comment]
Thanks a lot for the reply!
However, may I ask again for the dictionary resources?
This link is still unavailable now: http://dws.informatik.uni-mannheim.de/fileadmin/lehrstuehle/pi1/pi1/minie/wiki-freq-args-rels.zip (Am I using the correct link?)
Thanks a lot again for your time and patience. :)

**Comment by gkiril** [comment]
Here is the new link: 
https://www.uni-mannheim.de/media/Einrichtungen/dws/Files_Research/Software/MinIE/wiki-freq-args-rels.zip
